import { NextResponse } from 'next/server';
import { GoogleGenerativeAI } from '@google/generative-ai';

const genAI = new GoogleGenerativeAI(process.env.GEMINI_API_KEY!);

export async function POST(req: Request) {
  try {
    const body = await req.json();
    const { goal, targetUser, difficulty, onechainProducts, description } = body;

    // Validate all required fields
    if (!goal || !targetUser || !difficulty || !onechainProducts || !description) {
      return NextResponse.json(
        { success: false, error: 'All fields are required: goal, targetUser, difficulty, onechainProducts, description' },
        { status: 400 }
      );
    }

    const prompt = `You are a Web3 quest designer for the OneChain ecosystem. Your task is to create 5-7 sequential, educational quests based on the following campaign.

=== PRIMARY CONTEXT (Most Important) ===
Campaign Description: ${description}

=== Additional Context ===
- Campaign Name: ${goal}
- Target User Level: ${targetUser}
- Difficulty: ${difficulty}
- OneChain Products/Protocols: ${onechainProducts}

=== RULES ===
1. The "Campaign Description" above is your ABSOLUTE PRIMARY context. Every quest MUST directly relate to it.
2. Each quest's description MUST be written as an ordered list of clear, actionable steps — NOT a paragraph.
3. Use proof_type "TX_HASH" for on-chain quests (swaps, staking, minting, etc.) and "AUTO" for social/educational quests (reading, sharing, etc.).
4. Steps should be specific, mentioning exact UI elements, buttons, or contract actions the user needs to perform.
5. For ${difficulty} difficulty, adjust the complexity of steps accordingly.

Output ONLY a valid JSON array with this exact format (no markdown, no code blocks):
[
  {
    "step_number": 1,
    "title": "Short Quest Title",
    "description": "Brief one-line summary of the quest objective",
    "steps": [
      "Step 1: Navigate to ...",
      "Step 2: Click on ...",
      "Step 3: Confirm the transaction ..."
    ],
    "proof_type": "TX_HASH"
  }
]`;

    const model = genAI.getGenerativeModel({ model: "gemini-2.5-flash" });
    const result = await model.generateContent(prompt);
    let text = result.response.text();
    
    // Clean up markdown formatting often generated by LLMs
    text = text.replace(/```json/gi, '').replace(/```/g, '').trim();
    
    return NextResponse.json({ success: true, quests: JSON.parse(text) });
  } catch (error: any) {
    return NextResponse.json({ success: false, error: error.message }, { status: 500 });
  }
}